import type { Question, CurrentAffair, TnpscNotification, LeaderboardEntry, Achievement, Exam } from './types';

export const MOCK_EXAMS: Exam[] = [
  {
    id: '1', slug: 'group-1', name: 'TNPSC Group 1', nameTamil: 'TNPSC குரூப் 1',
    group: 'GROUP_1', description: 'Deputy Collector, DSP, District Registrar and other senior posts',
    vacancyCount: 68, examDate: '2026-08-15',
  },
  {
    id: '2', slug: 'group-2', name: 'TNPSC Group 2', nameTamil: 'TNPSC குரூப் 2',
    group: 'GROUP_2', description: 'Sub-Registrar, Municipal Commissioner, Assistant Section Officer',
    vacancyCount: 120, examDate: '2026-07-20',
  },
  {
    id: '3', slug: 'group-2a', name: 'TNPSC Group 2A', nameTamil: 'TNPSC குரூப் 2A',
    group: 'GROUP_2A', description: 'Personal Clerk, Assistant Section Officer (Non-Interview)',
    vacancyCount: 95, examDate: '2026-09-10',
  },
  {
    id: '4', slug: 'group-4', name: 'TNPSC Group 4', nameTamil: 'TNPSC குரூப் 4',
    group: 'GROUP_4', description: 'Village Administrative Officer, Junior Assistant, Bill Collector',
    vacancyCount: 2500, examDate: '2026-06-28',
  },
  {
    id: '5', slug: 'vao', name: 'TNPSC VAO', nameTamil: 'TNPSC வ.அ.ஒ',
    group: 'VAO', description: 'Village Administrative Officer',
    vacancyCount: 500, examDate: '2026-10-05',
  },
];

export const MOCK_QUESTIONS: Question[] = [
  {
    id: 'q1', type: 'MCQ',
    contentTamil: 'தமிழ்நாட்டின் தலைநகர் எது?',
    contentEnglish: 'What is the capital of Tamil Nadu?',
    options: [
      { id: 'a', textTamil: 'சென்னை', textEnglish: 'Chennai', isCorrect: true },
      { id: 'b', textTamil: 'கோயம்புத்தூர்', textEnglish: 'Coimbatore', isCorrect: false },
      { id: 'c', textTamil: 'மதுரை', textEnglish: 'Madurai', isCorrect: false },
      { id: 'd', textTamil: 'திருச்சிராப்பள்ளி', textEnglish: 'Tiruchirappalli', isCorrect: false },
    ],
    explanationTamil: 'தமிழ்நாட்டின் தலைநகர் சென்னை ஆகும். இது மாநிலத்தின் மிகப்பெரிய நகரமும் ஆகும்.',
    explanation: 'Chennai is the capital of Tamil Nadu and also the largest city in the state.',
    difficulty: 'EASY', isPYQ: true, year: 2020,
  },
  {
    id: 'q2', type: 'MCQ',
    contentTamil: 'வேதாரண்யம் உப்பு சத்தியாகிரகம் எந்த ஆண்டு நடந்தது?',
    contentEnglish: 'In which year did the Vedaranyam Salt Satyagraha take place?',
    options: [
      { id: 'a', textTamil: '1928', textEnglish: '1928', isCorrect: false },
      { id: 'b', textTamil: '1930', textEnglish: '1930', isCorrect: true },
      { id: 'c', textTamil: '1932', textEnglish: '1932', isCorrect: false },
      { id: 'd', textTamil: '1935', textEnglish: '1935', isCorrect: false },
    ],
    explanationTamil: 'ராஜாஜி தலைமையில் 1930-ல் வேதாரண்யம் உப்பு சத்தியாகிரகம் நடைபெற்றது.',
    explanation: 'The Vedaranyam Salt Satyagraha was led by Rajaji in 1930, inspired by Gandhi\'s Dandi March.',
    difficulty: 'MEDIUM', isPYQ: true, year: 2022,
  },
  {
    id: 'q3', type: 'MCQ',
    contentTamil: 'பூமியில் அதிக நீர் கொண்ட பெருங்கடல் எது?',
    contentEnglish: 'Which is the largest ocean on Earth?',
    options: [
      { id: 'a', textTamil: 'அட்லாண்டிக் பெருங்கடல்', textEnglish: 'Atlantic Ocean', isCorrect: false },
      { id: 'b', textTamil: 'இந்தியப் பெருங்கடல்', textEnglish: 'Indian Ocean', isCorrect: false },
      { id: 'c', textTamil: 'பசிபிக் பெருங்கடல்', textEnglish: 'Pacific Ocean', isCorrect: true },
      { id: 'd', textTamil: 'ஆர்க்டிக் பெருங்கடல்', textEnglish: 'Arctic Ocean', isCorrect: false },
    ],
    explanationTamil: 'பசிபிக் பெருங்கடல் உலகின் மிகப்பெரிய பெருங்கடல் ஆகும்.',
    explanation: 'The Pacific Ocean is the largest and deepest ocean on Earth.',
    difficulty: 'EASY', isPYQ: false,
  },
  {
    id: 'q4', type: 'MCQ',
    contentTamil: 'இந்திய அரசியலமைப்பின் பகுதி 21 எதனைப் பற்றியது?',
    contentEnglish: 'What does Part 21 of the Indian Constitution deal with?',
    options: [
      { id: 'a', textTamil: 'அரசியலமைப்பு திருத்தங்கள்', textEnglish: 'Constitutional Amendments', isCorrect: false },
      { id: 'b', textTamil: 'தற்காலிக, இடைக்கால, சிறப்பு விதிகள்', textEnglish: 'Temporary, Transitional & Special Provisions', isCorrect: true },
      { id: 'c', textTamil: 'தேர்தல் விதிகள்', textEnglish: 'Election Rules', isCorrect: false },
      { id: 'd', textTamil: 'அடிப்படை உரிமைகள்', textEnglish: 'Fundamental Rights', isCorrect: false },
    ],
    explanationTamil: 'பகுதி 21 தற்காலிக, இடைக்கால மற்றும் சிறப்பு விதிகளைப் பற்றியது.',
    difficulty: 'HARD', isPYQ: true, year: 2021,
  },
  {
    id: 'q5', type: 'MCQ',
    contentTamil: 'தமிழ்நாட்டில் அதிக மக்கள்தொகை கொண்ட மாவட்டம் எது?',
    contentEnglish: 'Which is the most populous district in Tamil Nadu?',
    options: [
      { id: 'a', textTamil: 'சென்னை', textEnglish: 'Chennai', isCorrect: true },
      { id: 'b', textTamil: 'விருதுநகர்', textEnglish: 'Virudhunagar', isCorrect: false },
      { id: 'c', textTamil: 'தூத்துக்குடி', textEnglish: 'Thoothukudi', isCorrect: false },
      { id: 'd', textTamil: 'நாமக்கல்', textEnglish: 'Namakkal', isCorrect: false },
    ],
    explanationTamil: '2011 மக்கள்தொகை கணக்கெடுப்பின்படி சென்னை மாவட்டமே அதிக மக்கள்தொகை கொண்டது.',
    difficulty: 'MEDIUM', isPYQ: true, year: 2019,
  },
  {
    id: 'q6', type: 'MCQ',
    contentTamil: 'தமிழ்நாட்டின் மிக நீளமான ஆறு எது?',
    contentEnglish: 'Which is the longest river in Tamil Nadu?',
    options: [
      { id: 'a', textTamil: 'காவிரி', textEnglish: 'Kaveri', isCorrect: true },
      { id: 'b', textTamil: 'வைகை', textEnglish: 'Vaigai', isCorrect: false },
      { id: 'c', textTamil: 'தாமிரபரணி', textEnglish: 'Thamirabarani', isCorrect: false },
      { id: 'd', textTamil: 'பாலாறு', textEnglish: 'Palar', isCorrect: false },
    ],
    explanationTamil: 'காவிரி ஆறு தமிழ்நாட்டின் மிக நீளமான ஆறு ஆகும்.',
    explanation: 'The Kaveri is the longest river flowing through Tamil Nadu.',
    difficulty: 'EASY', isPYQ: true, year: 2021,
  },
  {
    id: 'q7', type: 'MCQ',
    contentTamil: 'இந்திய அரசியலமைப்பின் எத்தனை அட்டவணைகள் உள்ளன?',
    contentEnglish: 'How many schedules does the Indian Constitution have?',
    options: [
      { id: 'a', textTamil: '10', textEnglish: '10', isCorrect: false },
      { id: 'b', textTamil: '12', textEnglish: '12', isCorrect: true },
      { id: 'c', textTamil: '11', textEnglish: '11', isCorrect: false },
      { id: 'd', textTamil: '9', textEnglish: '9', isCorrect: false },
    ],
    explanationTamil: 'இந்திய அரசியலமைப்பில் 12 அட்டவணைகள் உள்ளன.',
    explanation: 'The Indian Constitution currently contains 12 schedules.',
    difficulty: 'MEDIUM', isPYQ: true, year: 2020,
  },
  {
    id: 'q8', type: 'MCQ',
    contentTamil: 'மனித உடலில் உள்ள மிகப்பெரிய எலும்பு எது?',
    contentEnglish: 'Which is the largest bone in the human body?',
    options: [
      { id: 'a', textTamil: 'தொடை எலும்பு (Femur)', textEnglish: 'Femur', isCorrect: true },
      { id: 'b', textTamil: 'தாடை எலும்பு', textEnglish: 'Mandible', isCorrect: false },
      { id: 'c', textTamil: 'விலா எலும்பு', textEnglish: 'Rib', isCorrect: false },
      { id: 'd', textTamil: 'முதுகெலும்பு', textEnglish: 'Spine', isCorrect: false },
    ],
    explanationTamil: 'தொடை எலும்பு (Femur) மனித உடலின் மிகப்பெரிய மற்றும் வலிமையான எலும்பு ஆகும்.',
    explanation: 'The femur (thigh bone) is the largest and strongest bone in the human body.',
    difficulty: 'EASY', isPYQ: false,
  },
  {
    id: 'q9', type: 'MCQ',
    contentTamil: 'தமிழ்நாட்டின் முதல் முதலமைச்சர் யார்?',
    contentEnglish: 'Who was the first Chief Minister of Tamil Nadu (Madras State)?',
    options: [
      { id: 'a', textTamil: 'கே. காமராஜ்', textEnglish: 'K. Kamaraj', isCorrect: false },
      { id: 'b', textTamil: 'பி.எஸ். குமாரசாமி ராஜா', textEnglish: 'P.S. Kumaraswamy Raja', isCorrect: true },
      { id: 'c', textTamil: 'சி. ராஜகோபாலாச்சாரி', textEnglish: 'C. Rajagopalachari', isCorrect: false },
      { id: 'd', textTamil: 'எம்.ஜி. ராமச்சந்திரன்', textEnglish: 'M.G. Ramachandran', isCorrect: false },
    ],
    explanationTamil: 'பி.எஸ். குமாரசாமி ராஜா 1947-ல் சென்னை மாநிலத்தின் முதல் முதலமைச்சராக பதவியேற்றார்.',
    explanation: 'P.S. Kumaraswamy Raja became the first Chief Minister of Madras State in 1947.',
    difficulty: 'HARD', isPYQ: true, year: 2018,
  },
  {
    id: 'q10', type: 'MCQ',
    contentTamil: 'பஞ்சாயத்து ராஜ் அமைப்பு இந்திய அரசியலமைப்பில் எந்த சட்டத் திருத்தத்தின் மூலம் சேர்க்கப்பட்டது?',
    contentEnglish: 'Which constitutional amendment introduced the Panchayati Raj system?',
    options: [
      { id: 'a', textTamil: '72வது திருத்தம்', textEnglish: '72nd Amendment', isCorrect: false },
      { id: 'b', textTamil: '73வது திருத்தம்', textEnglish: '73rd Amendment', isCorrect: true },
      { id: 'c', textTamil: '74வது திருத்தம்', textEnglish: '74th Amendment', isCorrect: false },
      { id: 'd', textTamil: '71வது திருத்தம்', textEnglish: '71st Amendment', isCorrect: false },
    ],
    explanationTamil: '73வது அரசியலமைப்புத் திருத்தம் (1992) பஞ்சாயத்து ராஜ் அமைப்பை அறிமுகப்படுத்தியது.',
    explanation: 'The 73rd Constitutional Amendment (1992) established the Panchayati Raj system.',
    difficulty: 'MEDIUM', isPYQ: true, year: 2019,
  },
  {
    id: 'q11', type: 'MCQ',
    contentTamil: 'ஒளிச்சேர்க்கை நிகழும் தாவர பகுதி எது?',
    contentEnglish: 'In which part of the plant does photosynthesis primarily occur?',
    options: [
      { id: 'a', textTamil: 'வேர்', textEnglish: 'Root', isCorrect: false },
      { id: 'b', textTamil: 'இலை', textEnglish: 'Leaf', isCorrect: true },
      { id: 'c', textTamil: 'தண்டு', textEnglish: 'Stem', isCorrect: false },
      { id: 'd', textTamil: 'பூ', textEnglish: 'Flower', isCorrect: false },
    ],
    explanationTamil: 'இலைகளில் உள்ள பசையம் (chlorophyll) ஒளிச்சேர்க்கைக்கு உதவுகிறது.',
    explanation: 'Chlorophyll in leaves enables photosynthesis to occur.',
    difficulty: 'EASY', isPYQ: false,
  },
  {
    id: 'q12', type: 'MCQ',
    contentTamil: 'தமிழ்நாட்டின் மிகப்பெரிய நீர்த்தேக்கம் எது?',
    contentEnglish: 'Which is the largest reservoir in Tamil Nadu?',
    options: [
      { id: 'a', textTamil: 'மேட்டூர் அணை', textEnglish: 'Mettur Dam', isCorrect: true },
      { id: 'b', textTamil: 'வைகை அணை', textEnglish: 'Vaigai Dam', isCorrect: false },
      { id: 'c', textTamil: 'பாப்பநாசம் அணை', textEnglish: 'Papanasam Dam', isCorrect: false },
      { id: 'd', textTamil: 'கிருஷ்ணகிரி அணை', textEnglish: 'Krishnagiri Dam', isCorrect: false },
    ],
    explanationTamil: 'மேட்டூர் அணை காவிரி ஆற்றின் மீது அமைக்கப்பட்ட தமிழ்நாட்டின் மிகப்பெரிய நீர்த்தேக்கம்.',
    explanation: 'Mettur Dam, built on the Kaveri river, is the largest reservoir in Tamil Nadu.',
    difficulty: 'MEDIUM', isPYQ: true, year: 2017,
  },
  {
    id: 'q13', type: 'MCQ',
    contentTamil: 'இந்தியாவின் தேசிய விளையாட்டு எது?',
    contentEnglish: 'What is the national sport of India?',
    options: [
      { id: 'a', textTamil: 'கிரிக்கெட்', textEnglish: 'Cricket', isCorrect: false },
      { id: 'b', textTamil: 'ஹாக்கி', textEnglish: 'Hockey', isCorrect: true },
      { id: 'c', textTamil: 'கபடி', textEnglish: 'Kabaddi', isCorrect: false },
      { id: 'd', textTamil: 'மல்யுத்தம்', textEnglish: 'Wrestling', isCorrect: false },
    ],
    explanationTamil: 'ஹாக்கி இந்தியாவின் பாரம்பரிய தேசிய விளையாட்டாக கருதப்படுகிறது.',
    explanation: 'Hockey is traditionally regarded as the national sport of India.',
    difficulty: 'EASY', isPYQ: false,
  },
  {
    id: 'q14', type: 'MCQ',
    contentTamil: 'தமிழக சட்டமன்றத்தில் உள்ள மொத்த உறுப்பினர்களின் எண்ணிக்கை எவ்வளவு?',
    contentEnglish: 'What is the total number of members in the Tamil Nadu Legislative Assembly?',
    options: [
      { id: 'a', textTamil: '224', textEnglish: '224', isCorrect: true },
      { id: 'b', textTamil: '234', textEnglish: '234', isCorrect: false },
      { id: 'c', textTamil: '200', textEnglish: '200', isCorrect: false },
      { id: 'd', textTamil: '210', textEnglish: '210', isCorrect: false },
    ],
    explanationTamil: 'தமிழ்நாடு சட்டமன்றத்தில் 234 தொகுதிகள் இருந்தாலும், மொத்த உறுப்பினர்கள் எண்ணிக்கை 234 ஆகும். (கவனம்: இது சரியான தகவலை சரிபார்க்க வேண்டும்)',
    explanation: 'The Tamil Nadu Legislative Assembly has 234 elected members.',
    difficulty: 'HARD', isPYQ: true, year: 2022,
  },
  {
    id: 'q15', type: 'MCQ',
    contentTamil: 'குளிர்காலத்தில் தண்ணீர் பனிக்கட்டியாக மாறும்போது அதன் கன அளவு என்னவாகும்?',
    contentEnglish: 'What happens to the volume of water when it freezes into ice?',
    options: [
      { id: 'a', textTamil: 'அதிகரிக்கும்', textEnglish: 'Increases', isCorrect: true },
      { id: 'b', textTamil: 'குறையும்', textEnglish: 'Decreases', isCorrect: false },
      { id: 'c', textTamil: 'மாறாது', textEnglish: 'Remains the same', isCorrect: false },
      { id: 'd', textTamil: 'பூஜ்ஜியமாகும்', textEnglish: 'Becomes zero', isCorrect: false },
    ],
    explanationTamil: 'நீர் பனிக்கட்டியாக மாறும்போது அதன் கன அளவு அதிகரிக்கிறது, அதனால் பனிக்கட்டி நீரில் மிதக்கிறது.',
    explanation: 'Water expands when it freezes, which is why ice floats on water.',
    difficulty: 'MEDIUM', isPYQ: false,
  },
  {
    id: 'q16', type: 'MCQ',
    contentTamil: 'சுயராஜ்ய இயக்கத்தை தொடங்கியவர் யார்?',
    contentEnglish: 'Who started the Home Rule Movement in India?',
    options: [
      { id: 'a', textTamil: 'மகாத்மா காந்தி', textEnglish: 'Mahatma Gandhi', isCorrect: false },
      { id: 'b', textTamil: 'அன்னி பெசன்ட்', textEnglish: 'Annie Besant', isCorrect: true },
      { id: 'c', textTamil: 'பாலகங்காதர திலகர்', textEnglish: 'Bal Gangadhar Tilak', isCorrect: false },
      { id: 'd', textTamil: 'லாலா லஜபதிராய்', textEnglish: 'Lala Lajpat Rai', isCorrect: false },
    ],
    explanationTamil: 'அன்னி பெசன்ட் மற்றும் திலகர் இணைந்து 1916-ல் சுயராஜ்ய இயக்கத்தை தொடங்கினர்.',
    explanation: 'Annie Besant, along with Tilak, launched the Home Rule Movement in 1916.',
    difficulty: 'MEDIUM', isPYQ: true, year: 2018,
  },
  {
    id: 'q17', type: 'MCQ',
    contentTamil: 'தமிழ்நாட்டின் வடகிழக்கு பருவமழை எந்த மாதங்களில் வீசும்?',
    contentEnglish: 'During which months does the northeast monsoon occur in Tamil Nadu?',
    options: [
      { id: 'a', textTamil: 'ஜூன்-செப்டம்பர்', textEnglish: 'June-September', isCorrect: false },
      { id: 'b', textTamil: 'அக்டோபர்-டிசம்பர்', textEnglish: 'October-December', isCorrect: true },
      { id: 'c', textTamil: 'மார்ச்-மே', textEnglish: 'March-May', isCorrect: false },
      { id: 'd', textTamil: 'ஜனவரி-பிப்ரவரி', textEnglish: 'January-February', isCorrect: false },
    ],
    explanationTamil: 'தமிழ்நாட்டின் பெரும்பகுதி மழை வடகிழக்கு பருவமழையால் (அக்டோபர்-டிசம்பர்) கிடைக்கிறது.',
    explanation: 'Tamil Nadu receives most of its rainfall from the northeast monsoon (Oct-Dec).',
    difficulty: 'EASY', isPYQ: true, year: 2021,
  },
  {
    id: 'q18', type: 'MCQ',
    contentTamil: 'இந்திய அரசியலமைப்பின் தந்தை என்று அழைக்கப்படுபவர் யார்?',
    contentEnglish: 'Who is known as the Father of the Indian Constitution?',
    options: [
      { id: 'a', textTamil: 'மகாத்மா காந்தி', textEnglish: 'Mahatma Gandhi', isCorrect: false },
      { id: 'b', textTamil: 'பி.ஆர். அம்பேத்கர்', textEnglish: 'B.R. Ambedkar', isCorrect: true },
      { id: 'c', textTamil: 'ஜவாஹர்லால் நேரு', textEnglish: 'Jawaharlal Nehru', isCorrect: false },
      { id: 'd', textTamil: 'சர்தார் வல்லபாய் படேல்', textEnglish: 'Sardar Vallabhbhai Patel', isCorrect: false },
    ],
    explanationTamil: 'வரைவுக் குழுவின் தலைவராக இருந்த பி.ஆர். அம்பேத்கர் இந்திய அரசியலமைப்பின் தந்தை என அழைக்கப்படுகிறார்.',
    explanation: 'Dr. B.R. Ambedkar, chairman of the Drafting Committee, is regarded as the Father of the Indian Constitution.',
    difficulty: 'EASY', isPYQ: true, year: 2020,
  },
  {
    id: 'q19', type: 'MCQ',
    contentTamil: 'மனித இரத்தத்தில் ஆக்ஸிஜனை எது கொண்டு செல்கிறது?',
    contentEnglish: 'What carries oxygen in human blood?',
    options: [
      { id: 'a', textTamil: 'வெள்ளை அணுக்கள்', textEnglish: 'White blood cells', isCorrect: false },
      { id: 'b', textTamil: 'சிவப்பு அணுக்கள் (Hemoglobin)', textEnglish: 'Red blood cells (Hemoglobin)', isCorrect: true },
      { id: 'c', textTamil: 'பிளேட்லெட்டுகள்', textEnglish: 'Platelets', isCorrect: false },
      { id: 'd', textTamil: 'பிளாஸ்மா', textEnglish: 'Plasma', isCorrect: false },
    ],
    explanationTamil: 'சிவப்பு அணுக்களில் உள்ள ஹீமோகுளோபின் ஆக்ஸிஜனை உடல் முழுவதும் கொண்டு செல்கிறது.',
    explanation: 'Hemoglobin in red blood cells transports oxygen throughout the body.',
    difficulty: 'EASY', isPYQ: false,
  },
  {
    id: 'q20', type: 'MCQ',
    contentTamil: 'தமிழ்நாட்டின் முதல் பெண் முதலமைச்சர் யார்?',
    contentEnglish: 'Who was the first female Chief Minister of Tamil Nadu?',
    options: [
      { id: 'a', textTamil: 'ஜெ. ஜெயலலிதா', textEnglish: 'J. Jayalalithaa', isCorrect: true },
      { id: 'b', textTamil: 'வசந்தா முத்துசாமி', textEnglish: 'Vasantha Muthusamy', isCorrect: false },
      { id: 'c', textTamil: 'தமிழரசி', textEnglish: 'Tamizharasi', isCorrect: false },
      { id: 'd', textTamil: 'ஜானகி ராமச்சந்திரன்', textEnglish: 'Janaki Ramachandran', isCorrect: false },
    ],
    explanationTamil: 'ஜெ. ஜெயலலிதா 1991-ல் தமிழ்நாட்டின் முதல் பெண் முதலமைச்சராக பதவியேற்றார்.',
    explanation: 'J. Jayalalithaa became the first female Chief Minister of Tamil Nadu in 1991.',
    difficulty: 'MEDIUM', isPYQ: true, year: 2019,
  },
  {
    id: 'q21', type: 'MCQ',
    contentTamil: 'பூமியில் காணப்படும் மிகவும் வேகமாக ஓடும் தரை விலங்கு எது?',
    contentEnglish: 'Which is the fastest land animal on Earth?',
    options: [
      { id: 'a', textTamil: 'சிங்கம்', textEnglish: 'Lion', isCorrect: false },
      { id: 'b', textTamil: 'சீட்டா', textEnglish: 'Cheetah', isCorrect: true },
      { id: 'c', textTamil: 'குதிரை', textEnglish: 'Horse', isCorrect: false },
      { id: 'd', textTamil: 'ஓட்டக்கம்பை பறவை', textEnglish: 'Ostrich', isCorrect: false },
    ],
    explanationTamil: 'சீட்டா மணிக்கு 100 கி.மீ வேகத்தில் ஓடக்கூடிய மிக வேகமான தரை விலங்கு.',
    explanation: 'The cheetah can run up to 100 km/h, making it the fastest land animal.',
    difficulty: 'EASY', isPYQ: false,
  },
  {
    id: 'q22', type: 'MCQ',
    contentTamil: 'இந்திய அரசியலமைப்பின் எந்தப் பிரிவு அவசரகாலத்தை அறிவிக்க அதிகாரம் தருகிறது?',
    contentEnglish: 'Which Article of the Indian Constitution empowers the President to declare a National Emergency?',
    options: [
      { id: 'a', textTamil: 'பிரிவு 356', textEnglish: 'Article 356', isCorrect: false },
      { id: 'b', textTamil: 'பிரிவு 352', textEnglish: 'Article 352', isCorrect: true },
      { id: 'c', textTamil: 'பிரிவு 360', textEnglish: 'Article 360', isCorrect: false },
      { id: 'd', textTamil: 'பிரிவு 370', textEnglish: 'Article 370', isCorrect: false },
    ],
    explanationTamil: 'பிரிவு 352, தேசிய அவசரகாலத்தை அறிவிக்க குடியரசுத் தலைவருக்கு அதிகாரம் தருகிறது.',
    explanation: 'Article 352 empowers the President to declare a National Emergency.',
    difficulty: 'HARD', isPYQ: true, year: 2022,
  },
  {
    id: 'q23', type: 'MCQ',
    contentTamil: 'தமிழ்நாட்டின் தேசிய பறவை சரணாலயம் என அழைக்கப்படும் இடம் எது?',
    contentEnglish: 'Which place in Tamil Nadu is famous as a bird sanctuary?',
    options: [
      { id: 'a', textTamil: 'வேடந்தாங்கல்', textEnglish: 'Vedanthangal', isCorrect: true },
      { id: 'b', textTamil: 'மறுதமலை', textEnglish: 'Marudamalai', isCorrect: false },
      { id: 'c', textTamil: 'குற்றாலம்', textEnglish: 'Courtallam', isCorrect: false },
      { id: 'd', textTamil: 'எலிய அணை', textEnglish: 'Aliyar Dam', isCorrect: false },
    ],
    explanationTamil: 'வேடந்தாங்கல் பறவை சரணாலயம் காஞ்சிபுரம் மாவட்டத்தில் அமைந்துள்ளது.',
    explanation: 'Vedanthangal Bird Sanctuary is located in Kanchipuram district, Tamil Nadu.',
    difficulty: 'MEDIUM', isPYQ: true, year: 2017,
  },
  {
    id: 'q24', type: 'MCQ',
    contentTamil: 'GST (பொருட்கள் மற்றும் சேவை வரி) இந்தியாவில் எப்போது அமலுக்கு வந்தது?',
    contentEnglish: 'When was GST (Goods and Services Tax) implemented in India?',
    options: [
      { id: 'a', textTamil: 'ஜூலை 1, 2017', textEnglish: 'July 1, 2017', isCorrect: true },
      { id: 'b', textTamil: 'ஏப்ரல் 1, 2016', textEnglish: 'April 1, 2016', isCorrect: false },
      { id: 'c', textTamil: 'ஜனவரி 1, 2018', textEnglish: 'January 1, 2018', isCorrect: false },
      { id: 'd', textTamil: 'ஆகஸ்ட் 15, 2017', textEnglish: 'August 15, 2017', isCorrect: false },
    ],
    explanationTamil: 'GST ஜூலை 1, 2017 முதல் இந்தியா முழுவதும் அமலுக்கு வந்தது.',
    explanation: 'GST was rolled out across India starting July 1, 2017.',
    difficulty: 'MEDIUM', isPYQ: true, year: 2018,
  },
  {
    id: 'q25', type: 'MCQ',
    contentTamil: 'பூமியின் சுற்றுப்பாதையில் சூரியனை ஒரு முறை சுற்ற எவ்வளவு நாட்கள் ஆகும்?',
    contentEnglish: 'How many days does the Earth take to complete one orbit around the Sun?',
    options: [
      { id: 'a', textTamil: '24 மணி நேரம்', textEnglish: '24 hours', isCorrect: false },
      { id: 'b', textTamil: '365.25 நாட்கள்', textEnglish: '365.25 days', isCorrect: true },
      { id: 'c', textTamil: '30 நாட்கள்', textEnglish: '30 days', isCorrect: false },
      { id: 'd', textTamil: '12 மாதங்கள் சரியாக', textEnglish: 'Exactly 12 months', isCorrect: false },
    ],
    explanationTamil: 'பூமி சூரியனை ஒரு முறை சுற்ற 365.25 நாட்கள் எடுக்கும், இதனால் ஒவ்வொரு 4 ஆண்டுகளுக்கும் ஒரு லீப் ஆண்டு வருகிறது.',
    explanation: 'Earth takes approximately 365.25 days to orbit the Sun, which is why we have a leap year every 4 years.',
    difficulty: 'EASY', isPYQ: false,
  },
  {
    id: 'q26', type: 'MCQ',
    contentTamil: 'சுதந்திர இந்தியாவின் முதல் பிரதமர் யார்?',
    contentEnglish: 'Who was the first Prime Minister of independent India?',
    options: [
      { id: 'a', textTamil: 'மகாத்மா காந்தி', textEnglish: 'Mahatma Gandhi', isCorrect: false },
      { id: 'b', textTamil: 'ஜவாஹர்லால் நேரு', textEnglish: 'Jawaharlal Nehru', isCorrect: true },
      { id: 'c', textTamil: 'சர்தார் படேல்', textEnglish: 'Sardar Patel', isCorrect: false },
      { id: 'd', textTamil: 'ராஜேந்திர பிரசாத்', textEnglish: 'Rajendra Prasad', isCorrect: false },
    ],
    explanationTamil: 'ஜவாஹர்லால் நேரு 1947-ல் சுதந்திர இந்தியாவின் முதல் பிரதமராக பதவியேற்றார்.',
    explanation: 'Jawaharlal Nehru became the first Prime Minister of independent India in 1947.',
    difficulty: 'EASY', isPYQ: true, year: 2016,
  },
  {
    id: 'q27', type: 'MCQ',
    contentTamil: 'தமிழ்நாட்டின் கடற்கரை நீளம் (கி.மீ) தோராயமாக எவ்வளவு?',
    contentEnglish: 'What is the approximate length of Tamil Nadu coastline (in km)?',
    options: [
      { id: 'a', textTamil: '650', textEnglish: '650', isCorrect: false },
      { id: 'b', textTamil: '1076', textEnglish: '1076', isCorrect: true },
      { id: 'c', textTamil: '850', textEnglish: '850', isCorrect: false },
      { id: 'd', textTamil: '500', textEnglish: '500', isCorrect: false },
    ],
    explanationTamil: 'தமிழ்நாடு சுமார் 1076 கி.மீ நீளமான கடற்கரையை கொண்டுள்ளது, இது இந்தியாவின் மாநிலங்களில் இரண்டாவது நீளமானது.',
    explanation: 'Tamil Nadu has a coastline of about 1076 km, the second-longest among Indian states.',
    difficulty: 'HARD', isPYQ: true, year: 2021,
  },
  {
    id: 'q28', type: 'MCQ',
    contentTamil: 'பேங்க் ஆஃப் இந்தியாவின் தலைமை அலுவலகம் எங்கு அமைந்துள்ளது?',
    contentEnglish: 'Where is the headquarters of the Reserve Bank of India (RBI) located?',
    options: [
      { id: 'a', textTamil: 'புது தில்லி', textEnglish: 'New Delhi', isCorrect: false },
      { id: 'b', textTamil: 'மும்பை', textEnglish: 'Mumbai', isCorrect: true },
      { id: 'c', textTamil: 'கொல்கத்தா', textEnglish: 'Kolkata', isCorrect: false },
      { id: 'd', textTamil: 'சென்னை', textEnglish: 'Chennai', isCorrect: false },
    ],
    explanationTamil: 'இந்திய ரிசர்வ் வங்கியின் (RBI) தலைமை அலுவலகம் மும்பையில் அமைந்துள்ளது.',
    explanation: 'The Reserve Bank of India (RBI) headquarters is located in Mumbai.',
    difficulty: 'MEDIUM', isPYQ: true, year: 2020,
  },
  {
    id: 'q29', type: 'MCQ',
    contentTamil: 'பொங்கல் பண்டிகை எந்த மாதத்தில் கொண்டாடப்படுகிறது?',
    contentEnglish: 'In which month is the Pongal festival celebrated?',
    options: [
      { id: 'a', textTamil: 'டிசம்பர்', textEnglish: 'December', isCorrect: false },
      { id: 'b', textTamil: 'ஜனவரி', textEnglish: 'January', isCorrect: true },
      { id: 'c', textTamil: 'பிப்ரவரி', textEnglish: 'February', isCorrect: false },
      { id: 'd', textTamil: 'மார்ச்', textEnglish: 'March', isCorrect: false },
    ],
    explanationTamil: 'பொங்கல் தைத் திருநாளாக ஜனவரி மாதத்தில் தமிழ்நாட்டில் கொண்டாடப்படுகிறது.',
    explanation: 'Pongal is celebrated in January, marking the Tamil harvest festival (Thai month).',
    difficulty: 'EASY', isPYQ: false,
  },
  {
    id: 'q30', type: 'MCQ',
    contentTamil: 'இந்திய தேசியக் கொடியில் உள்ள சக்கரத்தில் எத்தனை ஆரைகள் உள்ளன?',
    contentEnglish: 'How many spokes are there in the Ashoka Chakra on the Indian national flag?',
    options: [
      { id: 'a', textTamil: '22', textEnglish: '22', isCorrect: false },
      { id: 'b', textTamil: '24', textEnglish: '24', isCorrect: true },
      { id: 'c', textTamil: '26', textEnglish: '26', isCorrect: false },
      { id: 'd', textTamil: '20', textEnglish: '20', isCorrect: false },
    ],
    explanationTamil: 'இந்திய தேசியக் கொடியின் நடுவில் உள்ள அசோக சக்கரத்தில் 24 ஆரைகள் உள்ளன.',
    explanation: 'The Ashoka Chakra at the center of the Indian flag has 24 spokes.',
    difficulty: 'EASY', isPYQ: true, year: 2019,
  },
];

export const MOCK_CURRENT_AFFAIRS: CurrentAffair[] = [
  {
    id: 'ca1', date: '2026-06-13', category: 'TAMILNADU',
    title: 'Tamil Nadu Launches New Free Laptop Scheme for College Students',
    titleTamil: 'தமிழ்நாடு கல்லூரி மாணவர்களுக்கு புதிய இலவச மடிக்கணினி திட்டத்தை தொடங்கியது',
    summary: 'TN govt announces free laptops for 5 lakh college students under the "Kalaignar Magalir Urimai" scheme extension.',
    summaryTamil: 'தமிழக அரசு "கலைஞர் மகளிர் உரிமை" திட்ட விரிவாக்கத்தின் கீழ் 5 லட்சம் கல்லூரி மாணவர்களுக்கு இலவச மடிக்கணினி அறிவித்தது.',
    importanceLevel: 4,
  },
  {
    id: 'ca2', date: '2026-06-13', category: 'NATIONAL',
    title: 'India GDP Growth at 7.2% in Q1 FY27',
    titleTamil: 'இந்தியா 2027-ம் நிதியாண்டு முதல் காலாண்டில் 7.2% GDP வளர்ச்சி',
    summary: 'India records 7.2% GDP growth in Q1 FY27, driven by manufacturing and services sectors.',
    summaryTamil: 'உற்பத்தி மற்றும் சேவைத் துறைகளால் இயக்கப்பட்டு இந்தியா 7.2% GDP வளர்ச்சியைப் பதிவு செய்தது.',
    importanceLevel: 3,
  },
  {
    id: 'ca3', date: '2026-06-12', category: 'SCHEME',
    title: 'PM Vishwakarma Scheme Extended to 2029',
    titleTamil: 'PM விஸ்வகர்மா திட்டம் 2029 வரை நீட்டிக்கப்பட்டது',
    summary: 'Central govt extends PM Vishwakarma Scheme for artisans and craftspeople till 2029 with increased allocation.',
    summaryTamil: 'மத்திய அரகு கைவினைஞர்களுக்கான PM விஸ்வகர்மா திட்டத்தை அதிகரிக்கப்பட்ட ஒதுக்கீட்டுடன் 2029 வரை நீட்டித்தது.',
    importanceLevel: 4,
  },
  {
    id: 'ca4', date: '2026-06-12', category: 'ECONOMY',
    title: 'RBI Keeps Repo Rate Unchanged at 6.5%',
    titleTamil: 'RBI ரெப்போ விகிதத்தை 6.5%-ல் மாற்றமின்றி வைத்திருக்கிறது',
    summary: 'Reserve Bank of India maintains repo rate at 6.5% citing stable inflation outlook.',
    summaryTamil: 'நிலையான பணவீக்க கண்ணோட்டத்தை மேற்கோள்காட்டி RBI ரெப்போ விகிதத்தை 6.5%-ல் நிலைநிறுத்தியது.',
    importanceLevel: 3,
  },
  {
    id: 'ca5', date: '2026-06-11', category: 'SCIENCE',
    title: 'ISRO Launches Next-Gen Navigation Satellite',
    titleTamil: 'ISRO அடுத்த தலைமுறை வழிசெலுத்தல் செய்மதியை ஏவியது',
    summary: 'ISRO successfully launches NVS-02 navigation satellite from Sriharikota, enhancing India\'s GPS capabilities.',
    summaryTamil: 'ISRO ஸ்ரீஹரிக்கோட்டாவிலிருந்து NVS-02 வழிசெலுத்தல் செய்மதியை வெற்றிகரமாக ஏவியது.',
    importanceLevel: 4,
  },
];

export const MOCK_NOTIFICATIONS: TnpscNotification[] = [
  {
    id: 'n1', type: 'RECRUITMENT',
    title: 'TNPSC Group 4 Recruitment 2026 — 2500 Vacancies',
    titleTamil: 'TNPSC குரூப் 4 ஆட்சேர்ப்பு 2026 — 2500 காலிப்பணியிடங்கள்',
    description: 'Online application open for Group 4 posts including VAO, Junior Assistant, Bill Collector',
    sourceUrl: '#', publishedAt: '2026-06-10',
    examDate: '2026-08-28', vacancy: 2500, isUrgent: true,
  },
  {
    id: 'n2', type: 'EXAM_DATE',
    title: 'Group 2 Exam Date Announced — July 20, 2026',
    titleTamil: 'குரூப் 2 தேர்வு தேதி அறிவிக்கப்பட்டது — ஜூலை 20, 2026',
    sourceUrl: '#', publishedAt: '2026-06-09',
    examDate: '2026-07-20', isUrgent: false,
  },
  {
    id: 'n3', type: 'RESULT',
    title: 'Group 2A Written Exam Result Published',
    titleTamil: 'குரூப் 2A எழுத்துத் தேர்வு முடிவு வெளியிடப்பட்டது',
    sourceUrl: '#', publishedAt: '2026-06-08', isUrgent: false,
  },
  {
    id: 'n4', type: 'HALL_TICKET',
    title: 'VAO Exam Hall Tickets Available for Download',
    titleTamil: 'VAO தேர்வு ஹால் டிக்கெட் பதிவிறக்கம் கிடைக்கிறது',
    sourceUrl: '#', publishedAt: '2026-06-07', isUrgent: true,
  },
  {
    id: 'n5', type: 'ANSWER_KEY',
    title: 'Group 1 Prelims Answer Key Released',
    titleTamil: 'குரூப் 1 முன்தேர்வு விடை வெளியிடப்பட்டது',
    sourceUrl: '#', publishedAt: '2026-06-05', isUrgent: false,
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  { rank: 1, userId: 'u1', name: 'கார்த்திக் குமார்', score: 98.5, accuracy: 96 },
  { rank: 2, userId: 'u2', name: 'பிரியா ரமேஷ்', score: 97.2, accuracy: 94 },
  { rank: 3, userId: 'u3', name: 'Arjun Selvan', score: 96.8, accuracy: 93 },
  { rank: 4, userId: 'u4', name: 'தீபா சந்திரன்', score: 95.5, accuracy: 91 },
  { rank: 5, userId: 'u5', name: 'Vikram Rajan', score: 94.1, accuracy: 89 },
  { rank: 6, userId: 'u6', name: 'முருகன் பாண்டியன்', score: 93.7, accuracy: 88 },
  { rank: 7, userId: 'u7', name: 'Lakshmi Narayanan', score: 92.3, accuracy: 87 },
  { rank: 8, userId: 'u8', name: 'சங்கர் கிருஷ்ணன்', score: 91.0, accuracy: 85 },
  { rank: 9, userId: 'u9', name: 'Meena Subramaniam', score: 90.2, accuracy: 84 },
  { rank: 10, userId: 'u10', name: 'கவின் பிரசாத்', score: 89.5, accuracy: 83 },
];

export const MOCK_ACHIEVEMENTS: Achievement[] = [
  { id: 'a1', name: 'Beginnings', nameTamil: 'தொடக்கம்', description: 'Complete your first lesson', descTamil: 'உங்கள் முதல் பாடத்தை முடிக்கவும்', icon: 'Play', xpReward: 10, rarity: 'COMMON' },
  { id: 'a2', name: 'On Fire', nameTamil: 'நெருப்பு', description: '7-day study streak', descTamil: '7 நாள் படிப்புத் தொடர்ச்சி', icon: 'Flame', xpReward: 200, rarity: 'RARE' },
  { id: 'a3', name: 'Gold Standard', nameTamil: 'தங்கம்', description: 'Top 1% in any mock test', descTamil: 'எந்த மாக் தேர்விலும் முதல் 1%', icon: 'Trophy', xpReward: 500, rarity: 'EPIC' },
  { id: 'a4', name: 'Questioner', nameTamil: 'கேள்வி வீரர்', description: 'Ask 50 community questions', descTamil: '50 சமூக கேள்விகளைக் கேட்கவும்', icon: 'HelpCircle', xpReward: 100, rarity: 'RARE' },
  { id: 'a5', name: 'Helper', nameTamil: 'உதவியாளர்', description: 'Get 100 upvotes in community', descTamil: 'சமூகத்தில் 100 வாக்குகள்', icon: 'Heart', xpReward: 200, rarity: 'RARE' },
  { id: 'a6', name: 'Scholar', nameTamil: 'ஆய்வாளர்', description: 'Read 365 daily current affairs', descTamil: '365 அன்றாட நிகழ்வுகளைப் படிக்கவும்', icon: 'BookOpen', xpReward: 1000, rarity: 'LEGENDARY' },
];

// ===== 91 NEW TNPSC QUESTIONS =====
export const EXTRA_QUESTIONS: Question[] = [];
